package se.jensen.anton.springer.model;

import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * This is a JPA entity which corresponds to the "comments" table in the database.
 * Each Comment has id, text content, a creation timestamp, a reference to the post and a reference to the user who created it,
 */
@Entity
@Table(name = "comments")
public class Comment {
    /**
     * ID of the comment (primary key).
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Text content of the comment.
     * This must not be null.
     */
    @Column(name = "text", nullable = false)
    private String text;
    /**
     * Creation timestamp of the post.
     */
    @Column(name = "created_at")
    private LocalDateTime created;
    /**
     * The post to which this comment belongs.
     * This must not be null.
     * It means that many comments can belong to one post.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "post_id")
    private Post post;
    /**
     * The user who created this comment.
     * This must not be null.
     * It means that many comments can belong to one user.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * Constructs a {@link Comment} with a specific text and creation timestamp.
     *
     * @param text    Text of the comment
     * @param created Timestamp when the comment was created
     */
    public Comment(String text, LocalDateTime created) {
        this.text = text;
        this.created = created;
    }

    public Comment() {
    }

    /**
     * The creation timestamp will automatically be set before the post is stored in the database.
     */
    @PrePersist
    protected void onCreate() {
        created = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public LocalDateTime getCreated() {
        return created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
