package se.jensen.anton.springer.model;

import jakarta.persistence.*;

import java.time.Instant;

/**
 * Represents a friendship relationship between two users.
 * Each friendship has a sender, who sends the request, and a receiver, who receives the friendship request.
 * A friendship has a status, which can be PENDING, ACCEPTED, or DECLINED.
 * It can track the timestamp when the request was created and when the request was responded.
 */

@Entity
@Table(
        name = "friendship",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "friend_pair",
                        columnNames = {"sender_id", "receiver_id"}
                )
        }
)
public class Friendship {
    /**
     * Status of the friendship.
     * PENDING = request sent but not yet accepted.
     * ACCEPTED = request accepted.
     * DECLINED = request declined.
     */
    public enum Status {
        PENDING, ACCEPTED, DECLINED
    }

    /**
     * ID of the friendship (primary key).
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * The user who sent the friendship request.
     * This must not be null.
     */
    @ManyToOne
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    /**
     * The user who received the friendship request.
     * This must not be null.
     */
    @ManyToOne
    @JoinColumn(name = "receiver_id", nullable = false)
    private User receiver;
    /**
     * The current status of the friendship.
     * The default value is PENDING.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status = Status.PENDING;
    /**
     * Timestamp when the friendship was requested.
     * This must not be updated and cannot be updated.
     * The creation timestamp will automatically be set when the entity is created.
     */
    @Column(nullable = false, updatable = false)
    private Instant requestedAt = Instant.now();

    /**
     * Timestamp when the friendship request was responded.
     */
    private Instant respondedAt;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getSender() {
        return sender;
    }

    public void setSender(User sender) {
        this.sender = sender;
    }

    public User getReceiver() {
        return receiver;
    }

    public void setReceiver(User receiver) {
        this.receiver = receiver;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Instant getRequestedAt() {
        return requestedAt;
    }

    public void setRequestedAt(Instant requestedAt) {
        this.requestedAt = requestedAt;
    }

    public Instant getRespondedAt() {
        return respondedAt;
    }

    public void setRespondedAt(Instant respondedAt) {
        this.respondedAt = respondedAt;
    }
}
