package se.jensen.anton.springer.model;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * This is a JPA entity which corresponds to the "posts" table in the database.
 * Each Post has id, text content, a creation timestamp, a reference to the user who created it, and a list of comments related to the post.
 */
@Entity
@Table(name = "posts")
public class Post {
    /**
     * ID of the post (primary key).
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id = 0L;

    /**
     * Text of the post. This must not be null.
     */
    @Column(name = "text", nullable = false)
    private String text;

    /**
     * Creation timestamp of the post.
     */
    @Column(name = "created_at")
    private LocalDateTime created;

    /**
     * The user who created this post.
     * It means that many posts can belong to one user.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * A list of comments related to this post.
     * When a post is deleted, all comments related to the post are also deleted.
     */
    @OneToMany(mappedBy = "post", cascade = CascadeType.REMOVE)
    private List<Comment> comments;

    /**
     * Constructs a {@link Post} with a specific text and creation timestamp.
     *
     * @param text    Text of the post
     * @param created Timestamp when the post was created
     */
    public Post(String text, LocalDateTime created) {
        this.text = text;
        this.created = created;
    }

    public Post() {

    }

    /**
     * The creation timestamp will automatically be set before the post is stored in the database.
     */
    @PrePersist
    protected void onCreate() {
        this.created = LocalDateTime.now();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public LocalDateTime getCreated() {
        return created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public List<Comment> getComments() {
        return comments;
    }

    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }
}
