package se.jensen.anton.springer.model;

import jakarta.persistence.*;

import java.util.List;

/**
 * This is a JPA entity which corresponds to the "app_user" table in the database.
 */
@Entity
@Table(name = "app_user")

public class User {
    /**
     * ID of the user (primary key).
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username of the user.
     * Must be unique, must not be null and has a maximum length of 50 characters.
     */
    @Column(name = "username", unique = true, nullable = false, length = 50)
    private String username;
    /**
     * Email address of the user.
     * Must be unique, must not be null and has a maximum length of 60 characters.
     */
    @Column(name = "email", unique = true, nullable = false, length = 60)
    private String email;
    /**
     * Password of the user.
     * Must not be null and has a maximum length of 100 characters.
     */
    @Column(name = "password", nullable = false, length = 100)
    private String password;
    /**
     * Role of the user ("USER" or "ADMIN").
     * Must not be null and has a maximum length of 20 characters.
     */
    @Column(name = "role", nullable = false, length = 20)
    private String role;
    /**
     * Display name of the user.
     * Must not be null and has a maximum length of 30 characters.
     */
    @Column(name = "display_name", nullable = false, length = 30)
    private String displayName;
    /**
     * Biography of the user.
     * Must not be null and has a maximum length of 200 characters.
     */
    @Column(name = "bio", nullable = false, length = 200)
    private String bio;
    /**
     * Path to the profile image of the user.
     * This field is optional and has a maximum length of 100 characters.
     */
    @Column(name = "profile_image_path", length = 100)
    private String profileImagePath;
    /**
     * List of posts created by the user.
     * When a user is deleted, all posts related to the user are also deleted.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.REMOVE)
    private List<Post> posts;

    /**
     * Constructs a {@link User} with a specific username and password.
     *
     * @param username the user's username
     * @param password the user's password
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public User() {

    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getProfileImagePath() {
        return profileImagePath;
    }

    public void setProfileImagePath(String profileImagePath) {
        this.profileImagePath = profileImagePath;
    }

    public List<Post> getPosts() {
        return posts;
    }

    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }
}
